# Generated by Django 6.0.2 on 2026-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determinAnalisis', models.CharField(max_length=200, verbose_name='Análisis')),
                ('codigoAnalisis', models.IntegerField(verbose_name='Código del Análisis')),
            ],
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraSocial', models.CharField(max_length=400, verbose_name='Obra Social')),
                ('codigoOS', models.IntegerField(verbose_name='Código de OS')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellidoPaciente', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('dniPaciente', models.IntegerField(null=True, verbose_name='DNI')),
                ('numAfiliado', models.IntegerField(null=True, verbose_name='N° de Afiliado')),
                ('fechaOrden', models.DateField(null=True, verbose_name='Fecha de la Orden')),
                ('nombreAnalisis', models.CharField(max_length=200, null=True, verbose_name='Análisis')),
                ('codigoAnalisis', models.IntegerField(null=True, verbose_name='Codigo del Análisis')),
                ('nombreObraSocial', models.CharField(max_length=200, null=True, verbose_name='Obra Social')),
                ('codigoObraSocial', models.IntegerField(null=True, verbose_name='Código de OS')),
                ('nombreMedico', models.CharField(max_length=200, null=True, verbose_name='Nombre del Médico')),
                ('firmaMedico', models.BooleanField(null=True, verbose_name='Firma del Médico')),
                ('selloMedico', models.BooleanField(null=True, verbose_name='Sello del Médico')),
            ],
        ),
    ]
