# Generated by Django 6.0.2 on 2026-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOrden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpaciente',
            name='codigoAnalisis',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='nombreAnalisis',
            field=models.JSONField(default=list, null=True),
        ),
    ]
