# Generated by Django 6.0.2 on 2026-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOrden', '0002_alter_ordenpaciente_codigoanalisis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpaciente',
            name='apellidoPaciente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='codigoAnalisis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='codigoObraSocial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código de OS'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='dniPaciente',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='fechaOrden',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Orden'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='firmaMedico',
            field=models.BooleanField(blank=True, null=True, verbose_name='Firma del Médico'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='nombreAnalisis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='nombreMedico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Médico'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='nombreObraSocial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='nombrePaciente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='numAfiliado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='N° de Afiliado'),
        ),
        migrations.AlterField(
            model_name='ordenpaciente',
            name='selloMedico',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sello del Médico'),
        ),
    ]
